### ISSUE TITLE
Unable to build on Ubuntu 16.04, linker error

### ISSUE THREAD

**Issue by jasonrobot** [jasonrobot/calc-rpn#6]
```
~/d/calc-rpn> make
gcc -c -g -Wall -o obj/tokenize.o src/tokenize.c
gcc -c -g -Wall -o obj/calculation_stack.o src/calculation_stack.c
gcc -c -g -Wall -o obj/token_stack.o src/token_stack.c
gcc -c -g -Wall -o obj/main.o src/main.c
gcc -c -g -Wall -o obj/hash.o src/hash.c
gcc -c -g -Wall -o obj/calc_functions.o src/calc_functions.c
gcc -g -Wall -lreadline -lm -o calc-rpn obj/tokenize.o obj/calculation_stack.o obj/token_stack.o obj/main.o obj/hash.o obj/calc_functions.o
obj/main.o: In function `main':
/home/jhowell/dev/calc-rpn/src/main.c:169: undefined reference to `readline'
obj/calc_functions.o: In function `modulo':
/home/jhowell/dev/calc-rpn/src/calc_functions.c:91: undefined reference to `floor'
/home/jhowell/dev/calc-rpn/src/calc_functions.c:91: undefined reference to `floor'
/home/jhowell/dev/calc-rpn/src/calc_functions.c:95: undefined reference to `floor'
/home/jhowell/dev/calc-rpn/src/calc_functions.c:95: undefined reference to `floor'
obj/calc_functions.o: In function `power':
/home/jhowell/dev/calc-rpn/src/calc_functions.c:101: undefined reference to `pow'
obj/calc_functions.o: In function `root':
/home/jhowell/dev/calc-rpn/src/calc_functions.c:107: undefined reference to `pow'
obj/calc_functions.o: In function `square_root':
/home/jhowell/dev/calc-rpn/src/calc_functions.c:113: undefined reference to `sqrt'
collect2: error: ld returned 1 exit status
makefile:34: recipe for target 'calc-rpn' failed
make: *** [calc-rpn] Error 1
```

```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

all libraries are installed. I tried running with the linker flags after the object file list in the makefile, and that seemed to fix it

**Comment by jasonrobot** [comment]
Should be fixed, see ref'd commit.

**Comment by jasonrobot** [comment]
Tested this again today, builds fine.
